In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\navin\Downloads\cardekho_dataset.csv.zip")
print(df)

       Unnamed: 0         car_name     brand     model  vehicle_age  \
0               0      Maruti Alto    Maruti      Alto            9
1               1    Hyundai Grand   Hyundai     Grand            5
2               2      Hyundai i20   Hyundai       i20           11
3               3      Maruti Alto    Maruti      Alto            9
4               4    Ford Ecosport      Ford  Ecosport            6
...           ...              ...       ...       ...          ...
15406       19537      Hyundai i10   Hyundai       i10            9
15407       19540    Maruti Ertiga    Maruti    Ertiga            2
15408       19541      Skoda Rapid     Skoda     Rapid            6
15409       19542  Mahindra XUV500  Mahindra    XUV500            5
15410       19543       Honda City     Honda      City            2

       km_driven seller_type fuel_type transmission_type  mileage  engine  \
0         120000  Individual    Petrol            Manual    19.70     796
1          20000  Individual    Petrol            Manual    18.90    1197
2          60000  Individual    Petrol            Manual    17.00    1197
3          37000  Individual    Petrol            Manual    20.92     998
4          30000      Dealer    Diesel            Manual    22.77    1498
...          ...         ...       ...               ...      ...     ...
15406      10723      Dealer    Petrol            Manual    19.81    1086
15407      18000      Dealer    Petrol            Manual    17.50    1373
15408      67000      Dealer    Diesel            Manual    21.14    1498
15409    3800000      Dealer    Diesel            Manual    16.00    2179
15410      13000      Dealer    Petrol         Automatic    18.00    1497

       max_power  seats  selling_price
0          46.30      5         120000
1          82.00      5         550000
2          80.00      5         215000
3          67.10      5         226000
4          98.59      5         570000
...          ...    ...            ...
15406      68.05      5         250000
15407      91.10      7         925000
15408     103.52      5         425000
15409     140.00      7        1225000
15410     117.60      5        1200000

[15411 rows x 14 columns]

In [2]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [3]:
df['fuel_type']

0        Petrol
1        Petrol
2        Petrol
3        Petrol
4        Diesel
          ...
15406    Petrol
15407    Petrol
15408    Diesel
15409    Diesel
15410    Petrol
Name: fuel_type, Length: 15411, dtype: object

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["transmission_type"] = le.fit_transform(df["transmission_type"])

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["fuel_type"] = le.fit_transform(df["fuel_type"])

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["seller_type"] = le.fit_transform(df["seller_type"])

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["brand"] = le.fit_transform(df["brand"])

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["model"] = le.fit_transform(df["model"])

In [9]:
df['brand']

0        18
1         8
2         8
3        18
4         6
         ..
15406     8
15407    18
15408    27
15409    17
15410     7
Name: brand, Length: 15411, dtype: int32

In [10]:
df['seller_type']

0        1
1        1
2        1
3        1
4        0
        ..
15406    0
15407    0
15408    0
15409    0
15410    0
Name: seller_type, Length: 15411, dtype: int32

In [11]:
df.drop('car_name', axis=1, inplace=True)

In [12]:
df

,Unnamed: 0,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,18,7,9,120000,1,4,1,19.70,796,46.30,5,120000
1,1,8,54,5,20000,1,4,1,18.90,1197,82.00,5,550000
2,2,8,118,11,60000,1,4,1,17.00,1197,80.00,5,215000
3,3,18,7,9,37000,1,4,1,20.92,998,67.10,5,226000
4,4,6,38,6,30000,0,1,1,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,8,117,9,10723,0,4,1,19.81,1086,68.05,5,250000
15407,19540,18,42,2,18000,0,4,1,17.50,1373,91.10,7,925000
15408,19541,27,77,6,67000,0,1,1,21.14,1498,103.52,5,425000
15409,19542,17,114,5,3800000,0,1,1,16.00,2179,140.00,7,1225000
15410,19543,7,25,2,13000,0,4,0,18.00,1497,117.60,5,1200000

In [15]:
df.shape

(15411, 13)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   brand              15411 non-null  int32
 2   model              15411 non-null  int32
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  int32
 6   fuel_type          15411 non-null  int32
 7   transmission_type  15411 non-null  int32
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int32(5), int64(6)
memory usage: 1.2 MB

In [17]:
df.isnull().sum()

Unnamed: 0           0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [18]:
df.duplicated().sum()

0